version: '3.8'

services:
  alertmanager-ntfy:
    image: luisnabais:alertmanager-ntfy:latest
    container_name: alertmanager-ntfy
    hostname: alertmanager-ntfy
    restart: unless-stopped
    environment:
      - NTFY_TOPIC=${NTFY_TOPIC}
      - NTFY_TOKEN=${NTFY_TOKEN}
    ports:
      - "5000:5000"
